-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [allowit_kernel]
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace allowit_kernel

/-- [allowit_kernel::policy::MAX_DAILY_LIMIT]
    Source: 'src/policy.rs', lines 5:0-5:44
    Visibility: public -/
@[global_simps, irreducible]
def policy.MAX_DAILY_LIMIT : Std.U64 := 50000000#u64

/-- [allowit_kernel::policy::DAY_SECONDS]
    Source: 'src/policy.rs', lines 6:0-6:36
    Visibility: public -/
@[global_simps, irreducible] def policy.DAY_SECONDS : Std.U64 := 86400#u64

/-- [allowit_kernel::policy_api::PolicyError]
    Source: 'src/policy_api.rs', lines 15:0-22:1
    Visibility: public -/
@[discriminant u32 [1,2,3,4,5,6]]
inductive policy_api.PolicyError where
| NotApproved : policy_api.PolicyError
| ZeroAmount : policy_api.PolicyError
| ParameterOutOfBounds : policy_api.PolicyError
| ClockWentBackwards : policy_api.PolicyError
| Overflow : policy_api.PolicyError
| DailyLimitExceeded : policy_api.PolicyError

/-- [allowit_kernel::policy::validate_daily_limit]:
    Source: 'src/policy.rs', lines 8:0-13:1
    Visibility: public -/
def policy.validate_daily_limit
  (value : Std.U64) :
  Result (core.result.Result Unit policy_api.PolicyError)
  := do
  if value > policy.MAX_DAILY_LIMIT
  then ok (core.result.Result.Err policy_api.PolicyError.ParameterOutOfBounds)
  else ok (core.result.Result.Ok ())

/-- [allowit_kernel::policy_api::Context]
    Source: 'src/policy_api.rs', lines 3:0-10:1
    Visibility: public -/
structure policy_api.Context where
  approved : Bool
  amount : Std.U64
  daily_limit : Std.U64
  spent : Std.U64
  spent_day : Std.U64
  now : Std.U64

/-- [allowit_kernel::policy::evaluate]:
    Source: 'src/policy.rs', lines 15:0-33:1
    Visibility: public -/
def policy.evaluate
  (ctx : policy_api.Context) :
  Result (core.result.Result Std.U64 policy_api.PolicyError)
  := do
  if ctx.approved
  then
    if ctx.amount = 0#u64
    then ok (core.result.Result.Err policy_api.PolicyError.ZeroAmount)
    else
      let r ← policy.validate_daily_limit ctx.daily_limit
      let cf ← core.result.Result.Insts.CoreOpsTry.branch r
      match cf with
      | core.ops.control_flow.ControlFlow.Continue _ =>
        let day ← ctx.now / policy.DAY_SECONDS
        if day < ctx.spent_day
        then
          ok (core.result.Result.Err policy_api.PolicyError.ClockWentBackwards)
        else
          let spent ← if day = ctx.spent_day
                        then ok ctx.spent
                        else ok 0#u64
          let o ← lift (U64.checked_add spent ctx.amount)
          let r1 ← core.option.Option.ok_or o policy_api.PolicyError.Overflow
          let cf1 ← core.result.Result.Insts.CoreOpsTry.branch r1
          match cf1 with
          | core.ops.control_flow.ControlFlow.Continue val =>
            if val > ctx.daily_limit
            then
              ok (core.result.Result.Err
                policy_api.PolicyError.DailyLimitExceeded)
            else ok (core.result.Result.Ok val)
          | core.ops.control_flow.ControlFlow.Break residual =>
            core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
              Std.U64 (core.convert.FromSame policy_api.PolicyError) residual
      | core.ops.control_flow.ControlFlow.Break residual =>
        core.result.Result.Insts.CoreOpsTry_traitFromResidualResult.from_residual
          Std.U64 (core.convert.FromSame policy_api.PolicyError) residual
  else ok (core.result.Result.Err policy_api.PolicyError.NotApproved)

/-- [allowit_kernel::policy_api::{impl core::clone::Clone for allowit_kernel::policy_api::Context}::clone]:
    Source: 'src/policy_api.rs', lines 2:9-2:14
    Visibility: public -/
def policy_api.Context.Insts.CoreCloneClone.clone
  (self : policy_api.Context) : Result policy_api.Context := do
  ok self

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::clone::Clone for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:9-2:14 -/
@[reducible]
def policy_api.Context.Insts.CoreCloneClone : core.clone.Clone
  policy_api.Context := {
  clone := policy_api.Context.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::marker::Copy for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:16-2:20 -/
@[reducible]
def policy_api.Context.Insts.CoreMarkerCopy : core.marker.Copy
  policy_api.Context := {
  cloneInst := policy_api.Context.Insts.CoreCloneClone
}

/-- [allowit_kernel::policy_api::{impl core::fmt::Debug for allowit_kernel::policy_api::Context}::fmt]:
    Source: 'src/policy_api.rs', lines 2:22-2:27
    Visibility: public -/
def policy_api.Context.Insts.CoreFmtDebug.fmt
  (self : policy_api.Context) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  let dyn := Dyn.mk _ core.fmt.DebugBool self.approved
  let dyn1 := Dyn.mk _ core.fmt.DebugU64 self.amount
  let dyn2 := Dyn.mk _ core.fmt.DebugU64 self.daily_limit
  let dyn3 := Dyn.mk _ core.fmt.DebugU64 self.spent
  let dyn4 := Dyn.mk _ core.fmt.DebugU64 self.spent_day
  let dyn5 := Dyn.mk _ (core.fmt.DebugShared core.fmt.DebugU64) self.now
  let values :=
    Array.to_slice (Array.make 6#usize [ dyn, dyn1, dyn2, dyn3, dyn4, dyn5 ])
  let s ←
    lift (Array.to_slice
      (Array.make 6#usize [
        toStr "approved", toStr "amount", toStr "daily_limit", toStr "spent",
        toStr "spent_day", toStr "now"
        ]))
  core.fmt.Formatter.debug_struct_fields_finish f (toStr "Context") s values

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::fmt::Debug for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:22-2:27 -/
@[reducible]
def policy_api.Context.Insts.CoreFmtDebug : core.fmt.Debug policy_api.Context
  := {
  fmt := policy_api.Context.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::marker::StructuralPartialEq for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:29-2:38 -/
@[reducible]
def policy_api.Context.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq policy_api.Context := {
}

/-- [allowit_kernel::policy_api::{impl core::cmp::PartialEq<allowit_kernel::policy_api::Context> for allowit_kernel::policy_api::Context}::eq]:
    Source: 'src/policy_api.rs', lines 2:29-2:38
    Visibility: public -/
def policy_api.Context.Insts.CoreCmpPartialEqContext.eq
  (self : policy_api.Context) (other : policy_api.Context) : Result Bool := do
  if self.approved = other.approved
  then
    if self.amount = other.amount
    then
      if self.daily_limit = other.daily_limit
      then
        if self.spent = other.spent
        then
          if self.spent_day = other.spent_day
          then ok (self.now = other.now)
          else ok false
        else ok false
      else ok false
    else ok false
  else ok false

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::cmp::PartialEq<allowit_kernel::policy_api::Context> for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:29-2:38 -/
@[reducible]
def policy_api.Context.Insts.CoreCmpPartialEqContext : core.cmp.PartialEq
  policy_api.Context policy_api.Context := {
  eq := policy_api.Context.Insts.CoreCmpPartialEqContext.eq
}

/-- [allowit_kernel::policy_api::{impl core::cmp::Eq for allowit_kernel::policy_api::Context}::assert_fields_are_eq]:
    Source: 'src/policy_api.rs', lines 2:40-2:42
    Visibility: public -/
def policy_api.Context.Insts.CoreCmpEq.assert_fields_are_eq
  (self : policy_api.Context) : Result Unit := do
  ok ()

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::cmp::Eq for allowit_kernel::policy_api::Context}]
    Source: 'src/policy_api.rs', lines 2:40-2:42 -/
@[reducible]
def policy_api.Context.Insts.CoreCmpEq : core.cmp.Eq policy_api.Context := {
  partialEqInst := policy_api.Context.Insts.CoreCmpPartialEqContext
  assert_fields_are_eq :=
    policy_api.Context.Insts.CoreCmpEq.assert_fields_are_eq
}

/-- [allowit_kernel::policy_api::{impl core::clone::Clone for allowit_kernel::policy_api::PolicyError}::clone]:
    Source: 'src/policy_api.rs', lines 13:9-13:14
    Visibility: public -/
def policy_api.PolicyError.Insts.CoreCloneClone.clone
  (self : policy_api.PolicyError) : Result policy_api.PolicyError := do
  ok self

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::clone::Clone for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:9-13:14 -/
@[reducible]
def policy_api.PolicyError.Insts.CoreCloneClone : core.clone.Clone
  policy_api.PolicyError := {
  clone := policy_api.PolicyError.Insts.CoreCloneClone.clone
}

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::marker::Copy for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:16-13:20 -/
@[reducible]
def policy_api.PolicyError.Insts.CoreMarkerCopy : core.marker.Copy
  policy_api.PolicyError := {
  cloneInst := policy_api.PolicyError.Insts.CoreCloneClone
}

/-- [allowit_kernel::policy_api::{impl core::fmt::Debug for allowit_kernel::policy_api::PolicyError}::fmt]:
    Source: 'src/policy_api.rs', lines 13:22-13:27
    Visibility: public -/
def policy_api.PolicyError.Insts.CoreFmtDebug.fmt
  (self : policy_api.PolicyError) (f : core.fmt.Formatter) :
  Result ((core.result.Result Unit core.fmt.Error) × core.fmt.Formatter)
  := do
  match self with
  | policy_api.PolicyError.NotApproved =>
    core.fmt.Formatter.write_str f (toStr "NotApproved")
  | policy_api.PolicyError.ZeroAmount =>
    core.fmt.Formatter.write_str f (toStr "ZeroAmount")
  | policy_api.PolicyError.ParameterOutOfBounds =>
    core.fmt.Formatter.write_str f (toStr "ParameterOutOfBounds")
  | policy_api.PolicyError.ClockWentBackwards =>
    core.fmt.Formatter.write_str f (toStr "ClockWentBackwards")
  | policy_api.PolicyError.Overflow =>
    core.fmt.Formatter.write_str f (toStr "Overflow")
  | policy_api.PolicyError.DailyLimitExceeded =>
    core.fmt.Formatter.write_str f (toStr "DailyLimitExceeded")

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::fmt::Debug for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:22-13:27 -/
@[reducible]
def policy_api.PolicyError.Insts.CoreFmtDebug : core.fmt.Debug
  policy_api.PolicyError := {
  fmt := policy_api.PolicyError.Insts.CoreFmtDebug.fmt
}

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::marker::StructuralPartialEq for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:29-13:38 -/
@[reducible]
def policy_api.PolicyError.Insts.CoreMarkerStructuralPartialEq :
  core.marker.StructuralPartialEq policy_api.PolicyError := {
}

/-- [allowit_kernel::policy_api::{impl core::cmp::PartialEq<allowit_kernel::policy_api::PolicyError> for allowit_kernel::policy_api::PolicyError}::eq]:
    Source: 'src/policy_api.rs', lines 13:29-13:38
    Visibility: public -/
def policy_api.PolicyError.Insts.CoreCmpPartialEqPolicyError.eq
  (self : policy_api.PolicyError) (other : policy_api.PolicyError) :
  Result Bool
  := do
  let self1 := read_discriminant self
  let other1 := read_discriminant other
  ok (self1 = other1)

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::cmp::PartialEq<allowit_kernel::policy_api::PolicyError> for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:29-13:38 -/
@[reducible]
def policy_api.PolicyError.Insts.CoreCmpPartialEqPolicyError :
  core.cmp.PartialEq policy_api.PolicyError policy_api.PolicyError := {
  eq := policy_api.PolicyError.Insts.CoreCmpPartialEqPolicyError.eq
}

/-- Trait implementation: [allowit_kernel::policy_api::{impl core::cmp::Eq for allowit_kernel::policy_api::PolicyError}]
    Source: 'src/policy_api.rs', lines 13:40-13:42 -/
@[reducible]
impl_def policy_api.PolicyError.Insts.CoreCmpEq : core.cmp.Eq
  policy_api.PolicyError := {
  partialEqInst := policy_api.PolicyError.Insts.CoreCmpPartialEqPolicyError
  assert_fields_are_eq := core.cmp.Eq.assert_fields_are_eq.default
    policy_api.PolicyError.Insts.CoreCmpEq
}

end allowit_kernel
